zero-to-mastery/TheSurvey

- authors.txt
some comments can go here, right?
> nano commit

- authors.txt
> adding myself as author

- authors.txt
Added my username to the authors list, please let me in :)
> added myself to the authors list

- authors.txt
> track upstream, modify authors.txt

- authors.txt
> Added myself to authors.txt

- authors.txt
> added Pavel aka Kern

- authors.md
I just add myself to the list, please let me in :)
> adding my name and skills

- authors.md
Dayshift again, but I succeeded adding myself now ;-)
> adding myself

- authors.md
Hi Guy's
added my info, please check and merge if it's all okay.
Thanks!
> added my info to authors.md

- authors.md
Adding name and skills to authors list.
> added EricC to authors.md

- authors.md
Add my skillset into authors file
> Docs: Include juanx skills in authors

- .gitignore
- index.js
- package-lock.json
- package.json
sorry if jumping the gun, but a boilerplate small bit of code to get people moving
> Boilerplate server code

- app/db/mongoose.js
- app/model/Question.js
- app/model/Result.js
- app/model/Survey.js
- app/model/User.js
- package-lock.json
- package.json
I didn't fill out all of the fields that will be need on Question and Result. We will need to discuss what we want to store and how we want to to store it in these collections.
> DB config file and groundwork for Mongoose model

- app/db/mongoose.js
- app/model/user.spec.js
- package-lock.json
- package.json
> Fix package.json syntax

- app/routes/auth/userLogin.js
@SamirJouni Is this the proper way to set these up as microservices?
@Jagholin Do I have the right idea as far as connecting to your database?
> Added login functionality

- app/routes/auth/userLogin.js
@Jagholin This changes userLogin.js to interact with your database API instead of making calls directly to mongodb. Can you confirm that this is what you had in mind? Also, as you build out the API, can you put a list of the API endpoints in the wiki so we can easily find them and point our services at them. thanks!
@SamirJouni I've changed this to be more along the lines of microservices. Can you confirm that I'm on the right track with this? Also, do we need to configure the services to run on different ports on our local machines for testing, and then change the hostnames and port numbers when moving from the development to production? I think each service will have to be configured manually when deploying right?
> userLogin.js now points to api endpoint rather than database

- app/routes/auth/userSignup.js
- package-lock.json
- package.json
Adding following:
- express-session for session handling
- fixing missing axios package in package.json
- first version of userSignUp.js for Sign up handling - backend
> userSignUp.js ready for next step

- index.html
Hey, just testing if this works.
> new index html

- README.md
- server/.gitignore
- server/package-lock.json
- server/package.json
- server/routes/auth.js
- server/routes/user.js
- server/server.js
> Basic server setup

- models/surveys.js
Created a models folder with new schema for storing user surveys.
> added schema for user created surveys

- README.md
Hey everyone, I want to keep on learning right now but I didn't want to pass on the chance to contribute at least with something. Hope to be back soon with more meaningful contributions!
@SamirJouni
> Fix a small typo in README file.

- README.md
Instruction to run the server/frontend was not right.
The package.json in each directory says the correct command is "npm start" however we had "npm run". 
That is fixed.
> fixed some errors in readme.md

- README.md
> Fixed spelling error in Readme
